-bash-4.2$ cat ../config/config.yaml 
log: logs/declad.log
debug_out: logs/declad.debug
error: logs/declad.errors

source_server: &src_server eospublic.cern.ch
destination_server: *src_server

scanner:
    server: *src_server
    location:   /eos/experiment/neutplatform/protodune/dune/test/dropbox
    filename_patterns:
      -   "*.hdf5"
      -   "*.root"
      -   "*.test"
    # meta_suffix:        .json           # optional
    ls_command_template:    "xrdfs $server ls -l $location"         # $server and $location will be replaced in run time
    parse_re:               ^(?P<type>[a-z-])\S+\s+\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}\s+(?P<size>\d+)\s+(?P<path>\S+)$
    timeout:                60      # seconds

quarantine_location: /eos/experiment/neutplatform/protodune/dune/test/dropbox/quarantine
transfer_timeout: 180

max_movers:     100                      # default 10
    
metacat_dataset:    dune:all                # namespace:name

destination_root_path:  /eos/experiment/neutplatform/protodune/dune         # absolute

create_dirs_command_template:   "xrdfs $server mkdir -p $path"
copy_command_template:          "xrdcp --force --silent --tpc first $src_url $dst_url"
download_command_template:      "xrdcp --force --silent root://$server/$src_path $dst_path"
delete_command_template:        "xrdfs $server rm $path"

rucio:
    declare_to_rucio:   yes
    drop_rse:   DUNE_CERN_EOS            # Rucio name of the RSE where the data arrives being copied from the dropbox
    target_rses:                # RSEs to create replication rule to
    - DUNE_US_FNAL_DISK_STAGE
    dataset_did_template: "%(run_type)s:%(run_type)s_%(run_number)s"          # Python %-operation template, applied to the file metadata dict

metacat_url:     https://metacat.fnal.gov:9443/dune_meta_prod/app
samweb_url:     https://samweb.fnal.gov:8483/sam/dune/api           # optionel. If omited, do not declare to SAM

samweb:
    user:    dunepro
    url:     https://samweb.fnal.gov:8483/sam/dune/api
    cert:    /etc/grid-security/fts/fts-protodune-declad7-cert.pem
    key:     /etc/grid-security/fts/fts-protodune-declad7-key.pem 


web_gui:
        port:   8089
        site_title:  Declaration Daemon
        prefix: /declad7

graphite:
        host: filer-carbon.cern.ch
        port: 2004
        namespace: fts.protodune.protodune-declad7-declad 
        interval: 10
        bin: 60